pygame 2.1.2 (SDL 2.0.18, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html


/usr/local/lib/python3.9/site-packages/gym/utils/play.py:11: UserWarning: WARN: failed to set matplotlib backend, plotting will not work: No module named '_tkinter'
  logger.warn("failed to set matplotlib backend, plotting will not work: %s" % str(e))


After analyzing the image game we found :
    - image 210 x 160 x 3
    - ball 4 x 2
    - pad 4 * 16

We have decided to consider the game like a pong prototype, our goal is to send back the ball.
As we decided to use Q-learning. Our training are made from a discrete environment.
We first have to reduce our environment :
Only keep bottom from the paddle and before the first breakable block (see image -> ....)

In [1]:
import imageio
import numpy as np
import gym
from gym.utils.play import play


def callback(obs_t, obs_tp1, action, rew, done, info):
    # image  50 x 72 x 1 color.
    imageio.imwrite('outfile1.png', obs_t[94:194:2, 8:152:2, 1])
    if action != 0:
        print(info)
        print(action)


env = gym.make('Breakout-v0')
play(env, zoom=3, fps=12, callback=callback)
env.reset()
env.close()

pygame 2.1.2 (SDL 2.0.18, Python 3.9.10)
Hello from the pygame community. https://www.pygame.org/contribute.html


/usr/local/lib/python3.9/site-packages/gym/utils/play.py:11: UserWarning: WARN: failed to set matplotlib backend, plotting will not work: No module named '_tkinter'
  logger.warn("failed to set matplotlib backend, plotting will not work: %s" % str(e))
A.L.E: Arcade Learning Environment (version 0.7.4+069f8bd)
[Powered by Stella]
2022-03-20 21:00:29.767 Python[28693:1215164] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/kl/c5lh2mc52hbbmbk_l0df9cvw0000gn/T/org.python.python.savedState


{'lives': 5, 'episode_frame_number': 33, 'frame_number': 33}
1
{'lives': 5, 'episode_frame_number': 37, 'frame_number': 37}
1
{'lives': 5, 'episode_frame_number': 123, 'frame_number': 123}
1
{'lives': 4, 'episode_frame_number': 127, 'frame_number': 127}
1
{'lives': 4, 'episode_frame_number': 221, 'frame_number': 221}
1
{'lives': 4, 'episode_frame_number': 223, 'frame_number': 223}
1
{'lives': 3, 'episode_frame_number': 242, 'frame_number': 242}
1
{'lives': 3, 'episode_frame_number': 245, 'frame_number': 245}
1
{'lives': 3, 'episode_frame_number': 261, 'frame_number': 261}
1
{'lives': 3, 'episode_frame_number': 270, 'frame_number': 270}
1
{'lives': 3, 'episode_frame_number': 277, 'frame_number': 277}
1
{'lives': 3, 'episode_frame_number': 281, 'frame_number': 281}
1
{'lives': 3, 'episode_frame_number': 285, 'frame_number': 285}
1
{'lives': 3, 'episode_frame_number': 289, 'frame_number': 289}
1
{'lives': 3, 'episode_frame_number': 291, 'frame_number': 291}
1
{'lives': 3, 'episode_frame_n

After reduction,we have:
   - image ->  60 x 72 x 1
   - ball 2 x 1
   - pad 2 * 8

Our Q state is composed of :
       B - ball position
       P - pad position
       A - action possible : 3  ( left , stay , right )
       D - direction
N  = BxQxNxD
The final goal will be to try with different composition of B P D . In the aim to find which discretization is more efficiant

Before generalization. Let's make a first example.
We discretize our image :
60 and 72 can be divided both by 12.
For the direction of the ball we take 4 directions, bottom left - bottom right - top left - top right
Our Q state is composed of :
       B - ball position :  5 x 6 position = 30
       P - pad position : 6 position only horizontal
       A - action possible : 3  ( left , stay , right )
       D - direction  : 4
N = 30 x 6 x 3 x 4 = 2160

In [85]:
import numpy as np
import random

XB = 6
YB = 5
P = 6
A = 3
D = 4  #  considering : 0 top-left  1 top right ...
Q = np.zeros((P, XB, YB, D, A), dtype=float)
alpha = 0.8
# x,y,direction
moveBall = {
    0: (1, 1),  # 45 top right
    1: (1, -1),  # -45 bottom right
    2: (-1, -1),  # -135 bottom left
    3: (-1, 1)  # 135 top-left
}


def updateBall(x, y, d, pad):
    #
    xD, yD = moveBall[d]
    nd = d
    nX, nY = x + xD, y + yD

    if pad == nX and nY == 0 or YB - 1 == nY:
        nd = (d + 2) % 4

    # if
    elif (XB - 1 == nX and d == 0) or (nX == 0 and d == 3):
        nd = d + (-3 if XB - 1 == nX and d == 0 else +3)


    elif (XB - 1 == nX and d == 1) or (nX == 0 and d == 2):
        nd = d + (1 if XB - 1 == nX and d == 1 else -1)

    return nX, nY, nd


def rewards(xb, yb, p):
    if p == xb and yb == 0:
        return 3
    return -5 if newYB == 0 and newDB in [1, 2] else 0


...

# iterations

N = 1000
for i in range(N):
    ## Create the pad here random position =
    xPad = 2
    epsilon = 1
    xBall, yBall, dirBall = 2, 2, 3
    endStep = 12000
    while not ((yBall == 0 and dirBall in [1, 2]) or endStep == 0):
        # find the index of the max of the line of Q_state
        maxIndex = np.where(Q[xPad][xBall][yBall][dirBall] == max(Q[xPad][xBall][yBall][dirBall]))[0]
        #    np.argmax(Q[xPad][xBall][yBall][dirBall])

        # e greedy
        r = random.random()
        action = random.choice([0, 1, 2] if r < epsilon else maxIndex)
        epsilon -= 0.05

        newXP = xPad + (action - 1 if P - 1 > xPad > 0 else 0)
        newXB, newYB, newDB = updateBall(xBall, yBall, dirBall, newXP)
        reward = rewards(newXB, newYB, newXP)

        Q[xPad][xBall][yBall][dirBall][action] += alpha * (
                reward + max(Q[newXP][newXB][newYB][newDB]) - Q[xPad][xBall][yBall][dirBall][action])

        xPad = newXP
        xBall, yBall, dirBall = newXB, newYB, newDB
        endStep -= 1
    #   print("position pad :", xPad, "position ball :", xBall, yBall, dirBall)

print(Q)




[[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

   [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

   [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

   [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

   [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
    [-5.00000000e+00 -5.00000000e+00 -5.00000000e+00]
    [ 0.00000000e+00

In [ ]:
class IAQLearning :
    
    def __init__(self):
        ...
    
    def learn(self,step):
        ...
    def rewards(self):
        ...
    
    def updateBall(self):
        ...
        
    def findNextMove(newBall, newPad):
        ...

In [7]:
import gym
import numpy as np
import pyglet
from gym.utils.play import play

class Pad:
    def __init__(self, x):
        self.x = x

    def discretPad(self, width):
        return self.x // width


class Ball:
    def __init__(self, coord):
        self.x, self.y = coord
        self.dir = (0, 0)

    def setDirection(self, ball):
        self.dir = (self.x - ball.x, self.y - ball.y)

    # Give xBall,yBall,(direction)
    def discretBall(self, height, width):
        # temporary rescale direction for our usage
        xDir = self.dir[0] if self.dir[0] == 0 else self.dir[0] / abs(self.dir[0])
        yDir = self.dir[1] if self.dir[1] == 0 else self.dir[1] / abs(self.dir[1])
        return self.x // height, self.y // width, (xDir, yDir)


class Breakout:
    def __init__(self):
        self.lives = 5
        self.env = gym.make('Breakout-v0')
        self.env.reset()
        self.previousGrid = None
        self.needSpawn = True
        self.nextMove = -1

    def gridReshape(self, grid):
        return grid[74:194:2, 8:152:2, 1]

    # This method is used to set the ball on the grid.
    # Loop until ball spawn
    def spawnBall(self):
        obs, rew, d, inf = self.env.step(1)
        self.previousGrid = self.gridReshape(obs)
        self.env.render()
        ball = self.findBall(self.previousGrid)
        return ball is None

    def lose(self):
        self.needSpawn = True
        self.lives -= 1

    def play(self, IAQState):
        # While IA still has balls : play
        while self.lives > 0:
            if self.needSpawn:
                self.needSpawn = self.spawnBall()
                continue
            ball = self.findBall(self.previousGrid)
            obs, rew, d, inf = env.step(0 if self.nextMove == -1 else self.nextMove)
            grid = self.gridReshape(obs)
            self.env.render()
            newBall = self.findBall(grid)
            if newBall is None:
                self.lose()
                continue
            newPad = self.findPad(grid[59])
            newBall.setDirection(ball)
            self.nextMove = IAQState.findNextMove(newBall, newPad)
            self.previousGrid = grid
        self.env.close()    
        
    def findBall(self, grid):
        coordinates = [(colIndex, rowIndex) for rowIndex, rowArray in enumerate(grid)
                       for colIndex, colValue in enumerate(rowArray)
                       if colValue == 72 and self.emptyEdge(rowArray, colIndex)]
        return None if len(coordinates) == 0 else Ball(coordinates[0])

    def emptyEdge(self, rowArray, index):
        if index == 0:
            return rowArray[index + 1] != 72
        if index == 71:
            return rowArray[index - 1] != 72
        return rowArray[index + 1] != 72 and rowArray[index - 1] != 72

    def findPad(self, row):
        pad = [index for index, elem in enumerate(row) if
               elem == 72 and all(pixel == 72 for pixel in row[index:index + 8])]
        return Pad(pad[0])

game = Breakout()
game.play(None)


# Bon j'arrete chu ko la tout marche, faudrait code une petite classe generique pour le learning , j'ai creer les methode en haut, pour que ce soit plus facile a tester apres avec diffenrete configuration. 


2022-03-20 23:05:31.475 Python[29090:1240343] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/kl/c5lh2mc52hbbmbk_l0df9cvw0000gn/T/org.python.python.savedState
/usr/local/lib/python3.9/site-packages/gym/envs/atari/environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(


KeyboardInterrupt: 

In [38]:
def Qlearning(B, P, A, D, ballPos):
    ...


def direction(direction):
    #return {i:360/direction}
    ...
def findNextMove(xB, yB, dir, pad):
    print(xB, yB, dir, pad)
    return 0


def cond(col, row, grid):
    if grid[row][col] != 72:
        return False

    if col == 0:
        return grid[row][col + 1] != 72
    if col == 71:
        return grid[row][col - 1] != 72

    return grid[row][col + 1] != 72 and grid[row][col - 1] != 72


def cond2(col, grid):
    if grid[col] != 72:
        return False
    return all(pixel == 72 for pixel in grid[col:col + 8])


pos = []



# while lives > 0:
#     if len(pos) == 0:
#         obs, rew, d, inf = env.step(1)
#         i += 1
#         pos = [(col, row) for row in range(len(obs[74:194:2, 8:152:2, 1])) for col in
#                range(len(obs[74:194:2, 8:152:2, 1][0])) if cond(col, row, obs[74:194:2, 8:152:2, 1])]
#         previousObs = obs
#         nextMove = -1
#         done = False
#         env.render()
#         continue
#
#     grid = previousObs[74:194:2, 8:152:2, 1]
#     env.render()
#     prevPos = [(col, row) for row in range(len(grid)) for col in range(len(grid[0])) if cond(col, row, grid)]
#     obs, rew, d, inf = env.step(STAY if nextMove == -1 else nextMove)  # take a random action
#     grid2 = obs[74:194:2, 8:152:2, 1]
#     pos = [(col, row) for row in range(len(grid2)) for col in range(len(grid2[0])) if cond(col, row, grid2)]
#
#     if len(pos) == 0:
#         #   print(grid2)
#         #  with open('grid.txt', 'a') as outfileX:
#         #    np.savetxt(outfileX, delimiter=' ', X=grid2, fmt='%d')
#         done = True
#         lives -= 1
#         print(lives)
#         i = 0
#         continue
#     direction = (pos[0][0] - prevPos[0][0], pos[0][1] - prevPos[0][1])
#     #angle =
#     # derniere ligne et dois trouver
#
#     pad = [col for col in range(len(grid2[0])) if cond2(col, grid2[59])]
#     resizeDir = (direction[0] / abs(direction[0] if direction[0] != 0 else 1),
#                  direction[1] / abs(direction[1] if direction[1] != 0 else 1))
#     nextMove = findNextMove(pos[0][0] // 12, pos[0][1] // 10, resizeDir, pad[0] // 12)
#
#     previousObs = obs

# class BreakOutGame
#reset
#play
#askforpart


#[
# # with open('sub.txt', 'a') as outfileX:
#         sub = np.subtract(obs[74:194:2, 8:152:2, 1], previousObs[74:194:2, 8:152:2, 1])
#         np.savetxt(outfileX, delimiter=' ', X=sub, fmt='%d')
#     with open('obs.txt', 'a') as outfileX:
#         np.savetxt(outfileX, delimiter=' ', X=obs[74:194:2, 8:152:2, 1], fmt='%d')
#     with open('prev.txt', 'a') as outfileX:
#         np.savetxt(outfileX, delimiter=' ', X=previousObs[74:194:2, 8:152:2, 1], fmt='%d')
#]

